# Generated by Django 5.0.4 on 2026-05-06 07:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(max_length=50, verbose_name='Abbr.')),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A1', 'อนุบาล 1'), ('A2', 'อนุบาล 2'), ('A3', 'อนุบาล 3'), ('B1', 'ประถม 1'), ('B2', 'ประถม 2'), ('B3', 'ประถม 3'), ('B4', 'ประถม 4'), ('B5', 'ประถม 5'), ('B6', 'ประถม 6'), ('C1', 'มัธยม 1'), ('C2', 'มัธยม 2'), ('C3', 'มัธยม 3'), ('C4', 'มัธยม 4'), ('C5', 'มัธยม 5'), ('C6', 'มัธยม 6')], max_length=2)),
                ('section', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='apis.school')),
            ],
            options={
                'unique_together': {('school', 'grade', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='apis.classroom')),
            ],
            options={
                'unique_together': {('firstname', 'lastname')},
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('classrooms', models.ManyToManyField(related_name='teachers', to='apis.classroom')),
            ],
            options={
                'unique_together': {('firstname', 'lastname')},
            },
        ),
    ]
